{{- $root := . -}}

{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.image.name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.uploadSize }}
    nginx.ingress.kubernetes.io/configuration-snippet: |-
      add_header X-Frame-Options "SAMEORIGIN";
      add_header X-Content-Type-Options nosniff;
      add_header X-XSS-Protection 1;
      add_header X-Permitted-Cross-Domain-Policies none;
      proxy_hide_header X-Powered-By;
      server_tokens off;
      if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain; charset=utf-8';
        add_header 'Content-Length' 0;
        return 204;
      }
      if ($request_method = 'POST') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
      }
      if ($request_method = 'GET') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
      }
    nginx.ingress.kubernetes.io/limit-rpm: "{{ .Values.ingress.rateLimit }}"
spec:
  rules:
    - host: "{{ .Values.domain }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.image.name }}
              servicePort: http
    - host: "www.{{ .Values.domain }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.image.name }}
              servicePort: http
  tls:
    - hosts:
      - "{{ .Values.domain }}"
      - "www.{{ .Values.domain }}"
      secretName: "api-{{ .Values.slug}}-tls"
{{- end }}
